export const config = {
	POSTHOG_API_KEY: process.env.POSTHOG_API_KEY,
	POSTHOG_HOST: process.env.POSTHOG_HOST,
	WEB3_MODAL_PROJECT_ID: process.env.WEB3_MODAL_PROJECT_ID!,
	CONCERO_ASSETS_URI: process.env.CONCERO_ASSETS_URI!,
	CONCERO_DOMAIN_URL: process.env.CONCERO_DOMAIN_URL!,
	APP_IS_NOT_AVAILABLE: false,
	POOLS_ARE_NOT_AVAILABLE: false,
}
